import { e, icon, money, date, statusBadge, displayText, displayPrice, empty } from './shared.js';
import { charts, topProducts } from './charts.js';
export function analyticsView(s, dashboard) {
  const metrics = [[s.activeProducts,'Productos activos'],[s.units,'Unidades vendidas · mes'],[s.revenue.map(r => money(r.amount,r.currency)).join(' / ') || '—','Ingresos simulados'],[s.ordersCount,'Pedidos pendientes'],[s.lowStockProducts,'Productos con stock bajo']];
  return `<div data-snapshot="${s.id}"><div class="admin-period"><span>Resumen de ${e(s.period)}</span><span class="admin-badge">Datos ficticios · Sesión ${s.id}</span></div><div class="admin-metrics">${metrics.map(([value,label]) => `<article><span>${label}</span><strong>${e(value)}</strong></article>`).join('')}</div>${charts(s)}<div class="admin-bottom-grid">${topProducts(s)}${dashboard ? `<article class="admin-panel"><p class="eyebrow">EN LA TIENDA</p><h2>Actividad reciente</h2><ul class="admin-activity">${s.recentActivity.map(o => `<li><a href="#/admin/orders/${e(o.id)}"><strong>#${e(o.id)}</strong><small>${date(o.createdAt)} · ${e(money(o.total,o.currency))}</small></a>${statusBadge(o.status)}</li>`).join('')}</ul></article>` : `<article class="admin-panel admin-note"><p class="eyebrow">LECTURA DEL REPORTE</p><h2>Un mes, distintas miradas.</h2><p>Las barras, la evolución y el ranking representan las mismas unidades. Cada ingreso corresponde al precio base multiplicado por las unidades vendidas.</p><p>Al volver a Ventas se genera otra simulación. Los pedidos conservan su propio historial.</p></article>`}</div>${dashboard ? `<article class="admin-panel"><div class="admin-row"><h2>Alertas de inventario</h2><a href="#/admin/inventory">Revisar inventario →</a></div><div class="admin-alerts">${s.stockAlerts.map(r => `<a href="#/admin/inventory"><strong>${e(displayText(r.name))}</strong><span>${e(displayText(r.variantName))} · ${r.stock} unidades</span></a>`).join('') || empty('Todo está al día. No hay alertas de stock.')}</div></article>` : ''}</div>`;
}
export function productsView(products) {
  return `<div class="admin-row admin-toolbar"><p>${products.length} productos · Una colección compartida</p><button class="button" data-create>+ Nuevo producto</button></div><div class="admin-product-list">${products.map(p => `<article class="admin-product" data-product="${e(p.id)}"><div class="admin-product-image">${p.image ? `<img src="${e(p.image)}" alt="${e(displayText(p.name))}">` : `<span aria-hidden="true">${icon('leaf')}</span>`}</div><div class="admin-product-info"><span class="admin-muted">${e(displayText(p.category))}</span><h2>${e(displayText(p.name))}</h2><p>${e(displayPrice(p))} <small>· ${e(p.baseCurrency)}</small></p><div class="admin-product-meta"><span>${p.stock} en stock</span><span>${p.variants.length} variantes</span><span class="admin-badge ${p.active === false ? 'is-muted' : ''}">${p.active === false ? 'Inactivo' : 'Activo'}</span></div></div><div class="admin-product-actions"><label class="admin-switch"><input type="checkbox" role="switch" data-featured ${p.featured ? 'checked' : ''}> Destacado</label><div><button class="admin-action" data-edit>Editar</button><button class="admin-action" data-view>Ver</button><button class="admin-action" data-deactivate ${p.active === false ? 'disabled' : ''}>Desactivar</button></div></div></article>`).join('') || empty('Tu colección está lista para su primer producto.')}</div>`;
}
export function inventoryView(rows) {
  return `<p class="admin-muted admin-toolbar">El stock general y el de cada variante se editan por separado en esta demostración.</p><div class="admin-inventory">${rows.map((r,i) => `<form class="admin-stock-row" data-stock data-product="${e(r.productId)}" data-variant="${e(r.variantId || '')}"><div><strong>${e(displayText(r.name))}</strong><small>${e(displayText(r.variantName))}${r.active === false ? ' · Inactivo' : ''}</small></div><span class="admin-badge ${r.stock <= 5 ? 'is-warning' : ''}">${e(r.status)}</span><label class="admin-field" for="stock-${i}">Cantidad<input id="stock-${i}" name="stock" type="number" min="0" step="1" required value="${r.stock}"></label><button class="admin-action">Actualizar stock</button></form>`).join('') || empty('No hay existencias para mostrar.')}</div>`;
}
export function ordersView(orders, user) {
  return `<div class="admin-panel admin-table-wrap"><table><caption>Pedidos de la tienda · Mismo historial de Cuenta</caption><thead><tr><th>Pedido / cliente</th><th>Fecha</th><th>Total / moneda</th><th>Estado</th><th>Unidades</th><th>Detalle</th></tr></thead><tbody>${orders.map(o => `<tr><td><strong>#${e(o.id)}</strong><small>${e(user.firstName)} ${e(user.lastName)}</small></td><td>${date(o.createdAt)}</td><td>${e(money(o.total,o.currency))}<small>${e(o.currency)}</small></td><td>${statusBadge(o.status)}</td><td>${o.quantity}</td><td><a class="admin-action" href="#/admin/orders/${e(o.id)}">Ver detalle</a></td></tr>`).join('')}</tbody></table>${orders.length ? '' : empty('Todavía no hay pedidos.')}</div>`;
}
export function orderDetailView(order, user) {
  return `<a class="admin-back" href="#/admin/orders">← Volver a pedidos</a><article class="admin-panel"><div class="admin-row"><div><p class="eyebrow">PEDIDO #${e(order.id)}</p><h2>${e(user.firstName)} ${e(user.lastName)}</h2><p>${date(order.createdAt)} · ${e(user.email)}</p></div>${statusBadge(order.status)}</div><ul class="admin-order-items">${order.items.map(item => `<li><div><strong>${e(displayText(item.product?.name) || 'Producto no disponible')}</strong><small>${e(displayText(item.variant?.name) || item.variantId)} · ${item.quantity} × ${e(money(item.unitPrice,order.currency))}</small></div><strong>${e(money(item.subtotal,order.currency))}</strong></li>`).join('')}</ul><div class="admin-row"><span>${order.quantity} unidades · ${e(order.currency)}</span><h2>${e(money(order.total,order.currency))}</h2></div><h3 class="admin-space">Dirección del pedido</h3><p>${e(order.shippingAddress.recipientName)} · ${e(order.shippingAddress.addressLine)} · ${e(order.shippingAddress.city)}<br>${e(order.shippingAddress.phone)}</p></article>`;
}
