import { e, money, date, dateTime, displayText, icon, statusBadge, addressText, empty, progressBar } from './shared.js';
function itemView(item, currency, detail = false) {
  const name = item.product ? displayText(item.product.name) : 'Producto no disponible';
  return `<li class="account-order-item"><span class="account-product-mark">${item.product?.image ? `<img src="${e(item.product.image)}" alt="${e(name)}">` : icon('leaf')}</span><span><strong>${e(name)}</strong><small>${e(item.variant ? displayText(item.variant.name) : item.variantId)} · Cantidad: ${item.quantity}</small>${detail ? `<small>${e(money(item.unitPrice, currency))} por unidad</small>` : ''}</span><strong>${e(money(item.subtotal, currency))}</strong></li>`;
}
export function orderCard(order, tracking, history = false) {
  return `<article class="account-panel account-order"><div class="account-row"><div><h3>#${e(order.id)}</h3><p class="account-muted">${date(order.createdAt)} · ${order.quantity} unidades</p></div>${statusBadge(tracking ? 'Seguimiento activo' : order.status)}</div><ul class="account-order-items">${order.items.map(item => itemView(item, order.currency)).join('')}</ul>${tracking ? `<p class="account-tracking-status">${e(tracking.status)}</p>${progressBar(tracking)}<p class="account-muted">Entrega estimada (simulada): ${e(tracking.estimatedDelivery.split(' / ').map(date).join(' – '))}</p>` : ''}<div class="account-row account-order-footer"><strong>Total ${e(money(order.total, order.currency))}</strong><a class="account-link" href="#/account/${history ? 'history' : 'tracking'}/${e(order.id)}">${history ? 'Ver detalles' : 'Ver seguimiento'} ${icon('arrow')}</a></div></article>`;
}
export function ordersView(orders, trackings, history) {
  if (!orders.length) return empty(history ? 'Tu historia comienza aquí' : 'Todo está al día', history ? 'Tus pedidos anteriores aparecerán en este espacio.' : 'No tienes pedidos activos en este momento.', '#/catalog', 'Explorar productos');
  return `<div class="account-order-list">${orders.map(order => orderCard(order, trackings?.[order.id], history)).join('')}</div>`;
}
export function orderDetail(order, tracking) {
  const history = !tracking;
  return `<a class="account-link account-back" href="#/account/${history ? 'history' : 'tracking'}">← Volver a ${history ? 'historial' : 'seguimiento'}</a><article class="account-panel"><div class="account-row"><div><p class="eyebrow">${history ? 'Detalle del pedido' : 'Seguimiento simulado'}</p><h2>#${e(order.id)}</h2><p class="account-muted">Realizado el ${date(order.createdAt)}</p></div>${statusBadge(tracking ? 'Seguimiento activo' : order.status)}</div>${tracking ? `<div class="account-tracking-lead"><h3>${e(tracking.status)}</h3><p>Última actualización: ${dateTime(tracking.updatedAt)}</p>${progressBar(tracking)}<p>Entrega estimada: ${e(tracking.estimatedDelivery.split(' / ').map(date).join(' – '))}</p><small>Demostración ficticia, sin conexión con transportistas.</small></div><ol class="account-timeline">${tracking.events.map(event => `<li class="is-${event.status}"><span class="timeline-symbol" aria-hidden="true">${event.completed ? '✓' : event.status === 'current' ? '●' : '○'}</span><div><strong>${e(event.message)}</strong><small>${event.completed ? 'Completado' : event.status === 'current' ? 'Etapa actual' : 'Pendiente'}${event.timestamp ? ` · ${dateTime(event.timestamp)}` : ''}</small></div></li>`).join('')}</ol>` : ''}<h3>Productos de tu pedido</h3><ul class="account-order-items">${order.items.map(item => itemView(item, order.currency, true)).join('')}</ul><div class="account-total"><span>Total del pedido</span><strong>${e(money(order.total, order.currency))}</strong></div><div class="account-delivery"><h3>Dirección utilizada</h3><p>${e(order.shippingAddress.recipientName)}<br>${addressText(order.shippingAddress)}<br>${e(order.shippingAddress.phone)}</p></div></article>`;
}
