import { authService } from '../../services/auth.service.js';
import { t } from '../i18n/i18n.js';
import { escapeHtml as e } from '../../utils/html.js';
export function mountAuth(root,onAuthenticated){
  const abort=new AbortController();let register=false,busy=false;
  document.title='GT · GlobalizaT';document.documentElement.classList.add('auth-open');
  function paint(){root.innerHTML=`<section class="auth-screen" aria-labelledby="auth-title"><div class="auth-intro"><a class="auth-brand" href="#/home" aria-label="GlobalizaT"><span class="auth-monogram">GT<span>·</span></span><strong>GlobalizaT</strong></a><p class="eyebrow">${t('authTagline')}</p><h1>${t('authHeadline')}</h1><p>${t('authWelcome')}</p><div class="auth-orbit" aria-hidden="true"><span>GT</span></div></div><div class="auth-card"><p class="eyebrow">GLOBALIZAT</p><h2 id="auth-title">${t(register?'authCreate':'authLogin')}</h2><p class="auth-caption">${t(register?'authCreateText':'authLoginText')}</p><form class="auth-form">${register?`<div class="auth-name-row"><label>${t('firstName')}<input name="firstName" autocomplete="given-name" maxlength="80" required></label><label>${t('lastName')}<input name="lastName" autocomplete="family-name" maxlength="80" required></label></div>`:''}<label>${t('email')}<input name="email" type="email" autocomplete="username" maxlength="160" required></label><label>${t('password')}<input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" minlength="8" maxlength="128" required></label>${register?`<small>${t('authPasswordHint')}</small>`:''}<p role="alert" class="auth-error"></p><button class="button" type="submit">${t(register?'authCreate':'authLogin')}</button></form><p class="auth-switch">${t(register?'authHaveAccount':'authNew')} <button type="button" data-auth-switch>${t(register?'authLogin':'authCreate')}</button></p><div class="auth-demo"><button type="button" data-auth-demo>${t('authDemo')}</button><p>${t('authNoticeLocal')}</p></div></div></section>`;root.querySelector('input')?.focus({preventScroll:true});}
  async function run(operation){if(busy)return;busy=true;root.querySelectorAll('button').forEach(b=>b.disabled=true);root.querySelector('[role=alert]').textContent='';try{await operation();if(!abort.signal.aborted){root.querySelector('form')?.reset();await onAuthenticated();}}catch(error){if(!abort.signal.aborted)root.querySelector('[role=alert]').textContent=t(error.message.startsWith('auth')?error.message:'authFailure');}finally{busy=false;if(!abort.signal.aborted)root.querySelectorAll('button').forEach(b=>b.disabled=false);}}
  root.addEventListener('submit',event=>{if(!event.target.matches('.auth-form'))return;event.preventDefault();const form=event.target;if(!form.reportValidity())return;const data=Object.fromEntries(new FormData(form));run(()=>register?authService.register(data):authService.login(data.email,data.password));},{signal:abort.signal});
  root.addEventListener('click',event=>{if(event.target.closest('[data-auth-switch]')&&!busy){register=!register;paint();}if(event.target.closest('[data-auth-demo]'))run(()=>authService.loginDemo());},{signal:abort.signal});
  paint();return()=>{abort.abort();root.querySelector('form')?.reset();document.documentElement.classList.remove('auth-open');};
}
